import { useEffect, useState } from 'react'
import { getCoachTip, type CoachContext } from '../../lib/ai/coach'

type CoachPanelProps = {
  /** The hero's spot, or null when it is not the hero's turn. */
  context: CoachContext | null
  /** Changes once per hero decision point; drives an automatic re-fetch. */
  turnKey: string
  /** Whether it is currently the hero's turn. */
  active: boolean
  /**
   * A short, rule-based reaction to the hero's LAST move (Room 1 only). Shown after
   * the hero acts, while the opponents play and the hand resolves. Always available
   * with AI off because it is derived from the rule logic.
   */
  reaction?: string | null
  /**
   * A result-aware "what just happened" recap shown once the hand is OVER (Room 1
   * only). Unlike `reaction`, it factors in who won and what the opponent held, so
   * an in-the-moment "good call" is never the last word on a hand the hero lost.
   */
  resultReflection?: string | null
}

type Tip = { text: string; source: 'ai' | 'fallback' }

/**
 * Feature 1 coach. It does two things:
 *   - BEFORE the hero acts (their turn): asks `getCoachTip` for a grounded tip, with
 *     an "Ask coach" button to re-request. A badge shows AI vs the built-in rule tip.
 *   - AFTER the hero acts: shows a short, supportive `reaction` to the move just made.
 *
 * Everything works with AI off: the tip falls back to the rule-based hint, and the
 * reaction is always rule-derived.
 */
export function CoachPanel({ context, turnKey, active, reaction, resultReflection }: CoachPanelProps) {
  const [entry, setEntry] = useState<{ key: string; tip: Tip } | null>(null)
  const [nonce, setNonce] = useState(0)

  const requestKey = `${turnKey}#${nonce}`
  const fresh = entry?.key === requestKey
  const loading = active && Boolean(context) && !fresh
  const tip = entry?.tip ?? null

  useEffect(() => {
    if (!active || !context) return
    let cancelled = false
    getCoachTip(context).then((result) => {
      if (!cancelled) setEntry({ key: requestKey, tip: result })
    })
    return () => {
      cancelled = true
    }
  }, [requestKey, active, context])

  // Once the hand is over the recap wins; while opponents act, show the reaction to
  // the hero's last move. Both only appear when it is no longer the hero's turn.
  const showRecap = !active && Boolean(resultReflection)
  const showReaction = !active && !showRecap && Boolean(reaction)

  return (
    <section className="flex flex-col rounded-2xl border border-brand-200 bg-brand-50/60 p-4 shadow-card">
      <div className="mb-2 flex items-center justify-between">
        <h3 className="flex items-center gap-2 text-sm font-bold text-brand-800">
          <span aria-hidden>&clubs;</span> Coach
        </h3>
        {active && fresh && tip && (
          <span
            className={`rounded-full px-2 py-0.5 text-[0.6rem] font-bold uppercase tracking-wide ${
              tip.source === 'ai' ? 'bg-brand-600 text-white' : 'bg-slate-200 text-slate-600'
            }`}
            title={tip.source === 'ai' ? 'Tip generated by AI' : 'Built-in rule-based tip (AI offline)'}
          >
            {tip.source === 'ai' ? 'AI' : 'Built-in'}
          </span>
        )}
        {showRecap && (
          <span className="rounded-full bg-indigo-100 px-2 py-0.5 text-[0.6rem] font-bold uppercase tracking-wide text-indigo-700">
            Hand recap
          </span>
        )}
        {showReaction && (
          <span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[0.6rem] font-bold uppercase tracking-wide text-emerald-700">
            Your move
          </span>
        )}
      </div>

      <p className="min-h-[3rem] text-sm leading-relaxed text-slate-700" aria-live="polite">
        {showRecap
          ? resultReflection
          : showReaction
            ? reaction
            : !active
              ? 'Your coach will weigh in when it is your turn, and react after you act.'
              : loading
                ? 'Reading the spot…'
                : tip
                  ? tip.text
                  : 'Thinking about your spot…'}
      </p>

      <button
        type="button"
        disabled={!active || loading}
        onClick={() => setNonce((n) => n + 1)}
        className="mt-3 self-start rounded-xl border border-brand-300 bg-white px-3 py-2 text-xs font-bold text-brand-700 transition hover:bg-brand-50 disabled:opacity-50"
      >
        Ask coach
      </button>
    </section>
  )
}
