import { useEffect, useState } from 'react'
import { getCoachTip, type CoachContext } from '../../lib/ai/coach'

type CoachPanelProps = {
  /** The hero's spot, or null when it is not the hero's turn. */
  context: CoachContext | null
  /** Changes once per hero decision point; drives an automatic re-fetch. */
  turnKey: string
  /** Whether it is currently the hero's turn. */
  active: boolean
}

type Tip = { text: string; source: 'ai' | 'fallback' }

/**
 * Feature 1 coach. Automatically asks `getCoachTip` for a grounded tip at the
 * start of each hero turn, plus an "Ask coach" button to re-request. A small badge
 * shows whether the tip came from the AI or the built-in rule-based fallback — so
 * the panel always says something useful, even with AI Logic off.
 *
 * State is keyed to the request (turn + manual nonce) so "loading" is derived, not
 * set synchronously inside the effect.
 */
export function CoachPanel({ context, turnKey, active }: CoachPanelProps) {
  const [entry, setEntry] = useState<{ key: string; tip: Tip } | null>(null)
  const [nonce, setNonce] = useState(0)

  const requestKey = `${turnKey}#${nonce}`
  const fresh = entry?.key === requestKey
  const loading = active && Boolean(context) && !fresh
  const tip = entry?.tip ?? null

  useEffect(() => {
    if (!active || !context) return
    let cancelled = false
    getCoachTip(context).then((result) => {
      if (!cancelled) setEntry({ key: requestKey, tip: result })
    })
    return () => {
      cancelled = true
    }
  }, [requestKey, active, context])

  return (
    <section className="rounded-2xl border border-brand-200 bg-brand-50/60 p-4 shadow-card">
      <div className="mb-2 flex items-center justify-between">
        <h3 className="flex items-center gap-2 text-sm font-bold text-brand-800">
          <span aria-hidden>♣</span> Coach
        </h3>
        {active && fresh && tip && (
          <span
            className={`rounded-full px-2 py-0.5 text-[0.6rem] font-bold uppercase tracking-wide ${
              tip.source === 'ai' ? 'bg-brand-600 text-white' : 'bg-slate-200 text-slate-600'
            }`}
            title={tip.source === 'ai' ? 'Tip generated by AI' : 'Built-in rule-based tip (AI offline)'}
          >
            {tip.source === 'ai' ? 'AI' : 'Built-in'}
          </span>
        )}
      </div>

      <p className="min-h-[2.5rem] text-sm leading-relaxed text-slate-700" aria-live="polite">
        {!active
          ? 'Your coach will weigh in when it is your turn.'
          : loading
            ? 'Reading the spot…'
            : tip
              ? tip.text
              : 'Thinking about your spot…'}
      </p>

      <button
        type="button"
        disabled={!active || loading}
        onClick={() => setNonce((n) => n + 1)}
        className="mt-3 rounded-xl border border-brand-300 bg-white px-3 py-2 text-xs font-bold text-brand-700 transition hover:bg-brand-50 disabled:opacity-50"
      >
        Ask coach
      </button>
    </section>
  )
}
